### ISSUE TITLE
Can't shread entire drives

### ISSUE THREAD

**Issue by Mattwmaster58** [DevelopersTree/permadelete#47] opened 2022-06-24 01:32 UTC
Even when running with admin permission, my SATA USB dock drives aren't shred-able, it says I need administrator permission. Happens the same in drag n drop or file selector model.

**Comment by mhmd-azeez** [comment] 2022-06-24 08:46
Duplicate of #34, if you're willing to implement it I'll appreciate a PR

**Closed by mhmd-azeez** 2022-06-24 08:46 UTC
