### ISSUE TITLE
Can't use Permadelete, can only delete files to the recycle bin, my system is windows7。

### ISSUE THREAD

**Issue by Jon123468964** [DevelopersTree/permadelete#50] opened 2022-10-12 20:00 UTC
How to get administrator rights in windows 7?  I have tried many ways and have failed without exception.
![Uploading 74D4A178-10D4-4E07-8E05-35717CF123A9.jpeg…]()

**Comment by Jon123468964** [comment] 2022-10-12 20:01
![Uploading A5E6A4B9-5772-4A77-A10E-40923B3D4D6F.jpeg…]()

**Comment by Jon123468964** [comment] 2022-10-12 20:04
![image](https://user-images.githubusercontent.com/115492977/195437145-7d3125f3-91b1-438f-bb2c-36332a088a38.jpeg)

**Comment by Jon123468964** [comment] 2022-10-12 20:15
I'm really pissed off by this OS 😡

**Comment by Jon123468964** [comment] 2022-10-12 20:39
The software is very easy to use, but I'm a noob

**Comment by mhmd-azeez** [comment] 2022-10-12 21:32
Please stop spamming the repo. Duplicate of #49

**Closed by mhmd-azeez** 2022-10-12 21:32 UTC
